services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fastapi_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi_user -d fastapi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://fastapi_user:${POSTGRES_PASSWORD:-fastapi_password}@db:5432/fastapi_db
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      INIT_DB_ON_STARTUP: "true"
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "main.py", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:
